name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug files
        run: ls -la

      - name: Run script
        run: |
          if [ -f "./README.md" ]; then
            echo "README.md exists"
          else
            echo "README.md does not exist"
            exit 1
          fi
