name: 多架构 Derper Distroless构建 | Multiarch Derper Build

on:
  schedule:
    - cron: '0 1 * * *' # 每日自动同步
  workflow_dispatch:
    inputs:
      custom_version:
        description: "指定Derper版本 (e.g. 'v1.86.2')"
        required: false

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  derperbuild:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 检出代码 | Checkout Code
        uses: actions/checkout@v6

      - name: 🔐 登录 Docker Hub | Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        
      - name: 🛠️ 配置 Docker Buildx | Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: 🚀 构建并推送镜像 | Build and Push Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/derper-alpine.dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/derper:alpine
    
