name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 */36 * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "caddybuild.yml, vaultwardenbuild.yml"
          time_elapsed: "0"
