name: Auto Build from Source Test

on:
  workflow_dispatch: # 手动触发按钮
  schedule: # 每天北京时间10点自动构建
    - cron: '0 2 * * *'

jobs:
  cross-platform-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义要构建的 Dockerfile 列表及对应标签
        dockerfile: [
          { path: "docker/Dockerfile.alpine", tag: "alpine" },
          { path: "docker/Dockerfile.debian", tag: "debian" }
        ]
      fail-fast: false # 允许单个失败不影响其他构建

    permissions:
      contents: read
      packages: write

    steps:
      # 直接拉取源仓库代码
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: JinkaiNiu/vaultwarden-zh-cn
          ref: main # 可改为特定分支或tag
          path: source-code

      # 配置多架构构建环境
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # Docker 登录
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 多平台构建推送
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./source-code
          file: ./source-code/${{ matrix.dockerfile.path }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vaultwarden-lang:latest-${{ matrix.dockerfile.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/vaultwarden-lang:${{ github.run_number }}-${{ matrix.dockerfile.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
